version: "3"

networks:
  backend:

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    ports:
      - "8000:80"
    restart: always
    depends_on: 
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis
    networks:
      - backend

  nginx:
    image: jhonoryza/nginx:laravel-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./nginx/sample/index.html:/var/www/html/index.html
      - ~/Documents/www:/var/www
    networks:
      - backend

  php74:
    image: jhonoryza/php:ubuntu-7.4-composer-2
    container_name: php74
    restart: always
    working_dir: /var/www
    volumes:
      - ~/Documents/www:/var/www
    networks:
      - backend

  horizon74:
    image: jhonoryza/php:horizon-7.4
    container_name: horizon74
    restart: always
    working_dir: /var/www
    volumes:
      - ~/Documents/www:/var/www
      - ./horizon:/etc/supervisord.d
    networks:
      - backend

  php80:
    image: jhonoryza/php:ubuntu-8.0-composer-2
    container_name: php80
    restart: always
    working_dir: /var/www
    volumes:
      - ~/Documents/www:/var/www
    networks:
      - backend
