version: "3"

services:
  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  redis:
    image: redis:latest
    container_name: redis
    network_mode: "host"
    volumes:
      - ./redis:/var/lib/redis
